# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d92714cb081d043ba8db5313753368749b713b09e91438128c8c1dd82a2cd426faa842f4c3e6c36ff77eddf599c9635bd1eaaa371cf8c245deaff8df827269a0

test:
  secret_key_base: 9e0180c503ba200a19f91199fca9f56ea34e4e4c9ed950d0b9066b3ac51c574e32ab641a327e965115af071690f3531b55ed43f42d955c2ce8fc3a3ee078b5a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
